### ISSUE TITLE
Retorno de Função não esperado.

### ISSUE THREAD

**Issue by wxcorporations** [wxcorporations/Estudo-Js#1]
# **Ideia inicial!**

- get_listaInputs(classe, callback)
capturar os nós a partir de uma classe e retorna uma lista de nós, caso seja passado callback essa lista sera diferente. 

- par(numero)
recebe um numero caso seja par este numero e retornado pela função;

Estou tentando retornar uma lista com os números pares preenchidos nos inputs, passo **funcão par()** de callback só que **get_listaInputs(classe, callback)** retorna uma lista com undefined não sei o que esta ocorrendo

**Comment by wgbn** [comment]
Muita coisa estranha nesse seu código, mas eu faria isso assim, mais enxuto.
Ainda da pra reduzir mais, mas assim fica bom pra você entender:

``` javascript
(function () {
    function get_listaInputs(classe, callback) {
        var numeros = [];
        document.querySelectorAll(classe).forEach(function (_item) {
            if (_item.value && !isNaN(_item.value)) numeros.push(_item.value);
        });

        return callback && typeof callback == 'function' ? numeros.filter(callback) : numeros;
    }

    function par(numero) {
        return numero % 2 == 0 ? numero : false;
    }
    
    var result = get_listaInputs(".campos", par);
    console.log(result);
})();
```
